name: formfun_flutter_test
description: "Form&Fun Flutter Test"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
  fonts:
    - family: AktivGrotesk
      fonts:
        - asset: assets/font/AktivGrotesk_Bd.ttf
        - asset: assets/font/AktivGrotesk_Blk.ttf
        - asset: assets/font/AktivGrotesk_Hair.ttf
        - asset: assets/font/AktivGrotesk_Lt.ttf
        - asset: assets/font/AktivGrotesk_Md.ttf
        - asset: assets/font/AktivGrotesk_Rg.ttf
        - asset: assets/font/AktivGrotesk_SBd.ttf
        - asset: assets/font/AktivGrotesk_Th.ttf
        - asset: assets/font/AktivGrotesk_XBd.ttf